### ISSUE TITLE
still need to add custom operator?

### ISSUE THREAD

**Issue by ZHAIXINGZHAIYUE** [Tveek/mxnet-shufflenet#1]
still need to add custom operator?

**Comment by Tveek** [comment]
@ZHAIXINGZHAIYUE never needed,custom operator is c++ implementation

**Comment by ZHAIXINGZHAIYUE** [comment]
@Tveek thank you。我最近在尝试使用shufflenetv2去做一些人脸识别的任务，但是我发现相同计算量下，普通的resnet以及mobilenet的效果更好。对此，你有什么建议吗？
